language: csharp
solution: TradingBot.sln
dotnet: 2.1.400
script: # Modify the commands below to build your repository.
  - export PROJECT_NAME=TradingBot
  - export TEST_NAME=TradingBotTests
  - dotnet restore
  - dotnet build TradingBot
  - dotnet test TradingBotTests